"""add org details fields

Revision ID: e7307ede2630
Revises: 
Create Date: 2026-04-20 18:58:22.122715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'e7307ede2630'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_instance_memberships_instance_id'), table_name='instance_memberships')
    op.drop_index(op.f('ix_instance_memberships_user_id'), table_name='instance_memberships')
    op.drop_table('instance_memberships')
    op.drop_index(op.f('ix_instances_slug'), table_name='instances')
    op.drop_table('instances')
    op.add_column('organizations', sa.Column('address', sa.Text(), nullable=True))
    op.add_column('organizations', sa.Column('countries', postgresql.ARRAY(sa.Text()), nullable=True))
    op.add_column('organizations', sa.Column('industries', postgresql.ARRAY(sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'industries')
    op.drop_column('organizations', 'countries')
    op.drop_column('organizations', 'address')
    op.create_table('instance_memberships',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('instance_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['instance_id'], ['instances.id'], name=op.f('instance_memberships_instance_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('instance_memberships_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('instance_memberships_pkey')),
    sa.UniqueConstraint('user_id', 'instance_id', name=op.f('uq_instance_membership'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_instance_memberships_user_id'), 'instance_memberships', ['user_id'], unique=False)
    op.create_index(op.f('ix_instance_memberships_instance_id'), 'instance_memberships', ['instance_id'], unique=False)
    op.create_table('instances',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('slug', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('instances_organization_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('instances_pkey')),
    sa.UniqueConstraint('organization_id', 'slug', name=op.f('uq_instance_org_slug'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_instances_slug'), 'instances', ['slug'], unique=False)
    # ### end Alembic commands ###
